# Generated by Django 5.2.8 on 2025-11-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_remove_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['id'], 'verbose_name': 'Paramètres du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image"),
        ),
    ]
