# Generated by Django 5.2.8 on 2025-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_sitesettings_options_service_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image'),
        ),
    ]
