# Generated by Django 5.2.8 on 2025-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_remove_service_image_url_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, default='', verbose_name='Caractéristiques'),
        ),
    ]
